#!/bin/bash

# Get system information
USERNAME=$(whoami)
DATE=$(date "+%Y-%m-%d %H:%M:%S")
HOSTNAME=$(hostname)
OS=$(source /etc/os-release && echo "$PRETTY_NAME")
UPTIME=$(uptime -p)

# Get hardware information
CPU=$(lscpu | grep "Model name" | awk -F': ' '{print $2}')
RAM=$(free -h | awk '/Mem:/ {print $2}')
DISKS=$(lsblk -d -o model,size | grep -v "MODEL")
VIDEO=$(lspci | grep -i 'vga\|3d\|video' | cut -d ':' -f3-)

# Get network information
FQDN=$(hostname -f)
IP_ADDRESS=$(ip route get 8.8.8.8 | awk '{print $7; exit}')
GATEWAY=$(ip route | grep default | awk '{print $3}')
DNS_SERVER=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}' | tr '\n' ', ' | sed 's/, $//')

# Get system status
USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd ", ")
DISK_SPACE=$(df -h | grep "^/dev" | awk '{print $6, $4}' | paste -sd ", ")
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGES=$(uptime | awk -F'load average:' '{print $2}' | sed 's/^ //')
LISTENING_PORTS=$(ss -tuln | awk 'NR>1 {print $5}' | awk -F':' '{print $NF}' | sort -n | uniq | paste -sd ", ")
UFW_STATUS=$(sudo ufw status | grep "Status" | awk '{print $2}')

# Generate the report
echo ""
echo "System Report generated by $USERNAME, $DATE"
echo ""
echo "System Information"
echo "------------------"
echo "Hostname: $HOSTNAME"
echo "OS: $OS"
echo "Uptime: $UPTIME"
echo ""
echo "Hardware Information"
echo "--------------------"
echo "CPU: $CPU"
echo "RAM: $RAM"
echo "Disks: $DISKS"
echo "Video: $VIDEO"
echo ""
echo "Network Information"
echo "-------------------"
echo "FQDN: $FQDN"
echo "Host Address: $IP_ADDRESS"
echo "Gateway IP: $GATEWAY"
echo "DNS Server: $DNS_SERVER"
echo ""
echo "System Status"
echo "-------------"
echo "Users Logged In: $USERS"
echo "Disk Space: $DISK_SPACE"
echo "Process Count: $PROCESS_COUNT"
echo "Load Averages: $LOAD_AVERAGES"
echo "Listening Network Ports: $LISTENING_PORTS"
echo "UFW Status: $UFW_STATUS"
echo ""
